ocfVersion: 0.0.1
revision: 0.1.0
kind: Type
metadata:
  name: config
  prefix: cap.type.analytics.elasticsearch
  displayName: Elasticsearch instance config
  description: Defines configuration for Elasticsearch instance
  documentationURL: https://www.elastic.co/what-is/elasticsearch
  supportURL: https://github.com/elastic/elasticsearch/issues
  iconURL: https://helm.elastic.co/icons/elasticsearch.png
  maintainers:
    - email: team-dev@capact.io
      name: Capact Dev Team
      url: https://capact.io
  attributes:
    cap.core.attribute.workload.stateful:
      revision: 0.1.0

spec:
  jsonSchema:
    value: |-
      {
        "$schema": "http://json-schema.org/draft-07/schema",
        "type": "object",
        "title": "The schema for Elasticsearch configuration",
        "required": [
          "version",
          "host",
          "basicAuthSecretName",
          "port",
          "protocol"
        ],
        "definitions": {
          "semVer": {
            "type": "string",
            "minLength": 5,
            "pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$",
            "title": "Semantic Versioning version",
            "examples": [
              "1.19.0",
              "2.0.1-alpha1"
            ]
          },
          "hostname": {
            "type": "string",
            "format": "hostname",
            "title": "Hostname"
          },
          "port": {
            "type": "integer",
            "title": "Port",
            "minimum": 0,
            "maximum": 65535
          }
        },
        "properties": {
          "version": {
            "$ref": "#/definitions/semVer"
          },
          "protocol": {
            "type": "string"
          },
          "host": {
            "$ref": "#/definitions/hostname"
          },
          "basicAuthSecretName": {
            "type": "string"
          },
          "port": {
            "$ref": "#/definitions/port"
          }
        },
        "additionalProperties": false
      }
