ocfVersion: 0.0.1
revision: 0.1.0
kind: Interface
metadata:
  prefix: cap.interface.runner.argo
  name: run
  displayName: "Run"
  description: "Run action for Argo Runner"
  documentationURL: https://capact.io
  supportURL: https://capact.io
  maintainers:
    - email: team-dev@capact.io
      name: Capact Dev Team
      url: https://capact.io

spec:
  abstract: true # It cannot be implemented
  input:
    parameters:
      input-parameters:
        typeRef:
          path: cap.type.runner.argo.run-input
          revision: 0.1.0

    typeInstances:
      runner-context:
        typeRef:
          path: cap.core.type.runner.generic.context
          revision: 0.1.0
        verbs: [ "get" ]
  output: { }
