ocfVersion: 0.0.1
revision: 0.1.0
kind: Interface
metadata:
  prefix: cap.interface.database.postgresql
  name: create-db
  displayName: Create database
  description: Create database action for PostgreSQL
  documentationURL: https://www.postgresql.org/docs/
  supportURL: https://www.postgresql.org/
  iconURL: https://www.postgresql.org/media/img/about/press/elephant.png
  maintainers:
    - email: team-dev@capact.io
      name: Capact Dev Team
      url: https://capact.io

spec:
  input:
    typeInstances:
      postgresql:
        typeRef:
          path: cap.type.database.postgresql.config
          revision: 0.1.0
        verbs: ["get"]
    parameters:
      input-parameters:
        typeRef:
            path: cap.type.database.postgresql.database-input
            revision: 0.1.0

  output:
    typeInstances:
      database:
        typeRef:
          path: cap.type.database.postgresql.database
          revision: 0.1.0
