ocfVersion: 0.0.1
revision: 0.1.0
kind: Implementation
metadata:
  prefix: cap.implementation.capact.examples
  name: greet
  displayName: "Greet Capact"
  description: "Capact Greet Action"
  documentationURL: https://capact.dev
  supportURL: https://capact.dev
  license:
    name: "Apache 2.0"
  maintainers:
    - email: team-dev@capact.dev
      name: Capact Dev Team
      url: https://capact.dev

spec:
  appVersion: "1.0.x"
  outputTypeInstanceRelations: {}

  implements:
    - path: cap.interface.capactio.examples.greet
      revision: 0.1.0

  imports:
    - interfaceGroupPath: cap.interface.runner.argo
      alias: argo
      methods:
        - name: run
          revision: 0.1.0
    - interfaceGroupPath: cap.interface.capactio.examples
      alias: examples
      methods:
        - name: say
          revision: 0.1.0

  action:
    runnerInterface: argo.run
    args:
      workflow:
        entrypoint: hello
        templates:
        - name: hello
          steps:
            - - name: get-message
                capact-action: examples.say
            - - name: print
                template: print
                arguments:
                  artifacts:
                    - name: message
                      from: "{{steps.get-message.outputs.artifacts.message}}"

        - name: print
          inputs:
            artifacts:
              - name: message
                path: /tmp/message.yaml
          container:
            image: docker/whalesay:latest
            command: [sh, -c ]
            args: ["cowsay < /tmp/message.yaml"]
