ocfVersion: 0.0.1
revision: 0.1.0
kind: Implementation
metadata:
  prefix: cap.implementation.capactio.capact.validation.action
  name: passing-a
  license:
    name: "Apache 2.0"
  displayName: Passing Capact test action that uses default storage backend
  description: ""
  documentationURL: "https://capact.io"
  maintainers:
    - email: team-dev@capact.io
      name: Capact Dev Team
      url: https://capact.io

spec:
  appVersion: "1.x.x"

  implements:
    - path: cap.interface.capactio.capact.validation.action.passing
      revision: 0.1.0

  outputTypeInstanceRelations:
    testUpload:
      uses: []

  imports:
    - interfaceGroupPath: cap.interface.runner.argo
      alias: argo
      methods:
        - name: run
          revision: 0.1.0

  action:
    runnerInterface: argo.run
    args:
      workflow:
        entrypoint: main
        templates:
          - name: main
            steps:
              - - name: cp
                  template: cp
                  arguments:
                    artifacts:
                      - name: input
                        from: "{{workflow.outputs.artifacts.testInput}}"
                  capact-outputTypeInstances:
                    - name: testUpload
                      from: upload
                  capact-updateTypeInstances:
                    - name: testUpdate
                      from: update
          - name: cp
            inputs:
              artifacts:
                - name: input
                  path: /input
            outputs:
              artifacts:
                - name: upload
                  path: /upload
                - name: update
                  path: /update
            container:
              image: alpine:latest
              command: ["sh", "-c"]
              args: ["echo 'Implementation A' && cp /input /upload && cp /input /update && sleep 1"]
