ocfVersion: 0.0.1
revision: 0.1.0
kind: Implementation
metadata:
  prefix: cap.implementation.concourse.concourse
  name: install
  displayName: Install Concourse
  description: Action which installs Concourse via Helm chart
  documentationURL: https://concourse-ci.org/
  supportURL: https://concourse-ci.org/
  iconURL: https://concourse-ci.org/images/logo-white.svg
  license:
    name: "Apache 2.0"
  maintainers:
    - email: team-dev@capact.io
      name: Capact Dev Team
      url: https://capact.io

spec:
  appVersion: "7.x.x"

  additionalInput:
    typeInstances:
      postgresql:
        typeRef:
          path: cap.type.database.postgresql.config
          revision: 0.1.0
        verbs: [ "get" ]

  outputTypeInstanceRelations:
    concourse-config:
      uses:
        - concourse-helm-release
        - postgresql
        - database
        - user

  implements:
    - path: cap.interface.automation.concourse.install
      revision: 0.1.0

  requires:
    cap.core.type.platform:
      oneOf:
        - name: kubernetes
          revision: 0.1.0
    cap.core.type.hub.storage:
      allOf:
        - name: cap.type.helm.template.storage
          revision: 0.1.0
          alias: helm-template-storage

  imports:
    - interfaceGroupPath: cap.interface.runner.argo
      alias: argo
      methods:
        - name: run
          revision: 0.1.0
    - interfaceGroupPath: cap.interface.runner.helm
      alias: helm
      methods:
        - name: install
          revision: 0.1.0
    - interfaceGroupPath: cap.interface.database.postgresql
      alias: postgresql
      methods:
        - name: install
          revision: 0.1.0
        - name: create-user
          revision: 0.1.0
        - name: create-db
          revision: 0.1.0
    - interfaceGroupPath: cap.interface.templating.jinja2
      alias: jinja2
      methods:
        - name: template
          revision: 0.1.0

  action:
    runnerInterface: argo.run
    args:
      workflow:
        entrypoint: concourse-install
        templates:
          - name: concourse-install
            inputs:
              artifacts:
                - name: input-parameters
                - name: postgresql
                  optional: true
            outputs:
              artifacts:
                - name: concourse-config
                  from: "{{steps.resolve-value.outputs.artifacts.ti-artifact}}"
            steps:
              - - name: install-db
                  capact-when: postgresql == nil # conditional execution
                  capact-action: postgresql.install
                  capact-outputTypeInstances:
                    - name: postgresql
                      from: postgresql
                  arguments:
                    artifacts:
                      - name: input-parameters
                        raw:
                          data: |
                            superuser:
                              username: superuser
                            defaultDBName: postgres

              - - name: create-user
                  capact-action: postgresql.create-user
                  capact-outputTypeInstances:
                    - name: user
                      from: user
                  arguments:
                    artifacts:
                      - name: postgresql
                        from: "{{steps.install-db.outputs.artifacts.postgresql}}"
                      - name: input-parameters
                        raw:
                          data: |
                            name: concourse

              - - name: render-create-db-args
                  capact-action: jinja2.template
                  arguments:
                    artifacts:
                      - name: template
                        raw:
                          data: |
                            name: concoursedb
                            owner: "<@ name @>"
                      - name: input-parameters
                        from: "{{steps.create-user.outputs.artifacts.user}}"
                      - name: configuration
                        raw:
                          data: "unpackValue: true"

              - - name: create-db
                  capact-action: postgresql.create-db
                  capact-outputTypeInstances:
                    - name: database
                      from: database
                  arguments:
                    artifacts:
                      - name: postgresql
                        from: "{{steps.install-db.outputs.artifacts.postgresql}}"
                      - name: input-parameters
                        from: "{{steps.render-create-db-args.outputs.artifacts.render}}"

              - - name: prepare-parameters
                  template: prepare-parameters
                  arguments:
                    artifacts:
                      - name: input-parameters
                        from: "{{inputs.artifacts.input-parameters}}"
                      - name: db
                        from: "{{steps.install-db.outputs.artifacts.postgresql}}"
                      - name: database
                        from: "{{steps.create-db.outputs.artifacts.database}}"
                      - name: user
                        from: "{{steps.create-user.outputs.artifacts.user}}"

              - - name: render-helm-args
                  capact-action: jinja2.template
                  arguments:
                    artifacts:
                      - name: template
                        raw:
                          data: |
                            generateName: true
                            chart:
                              name: "concourse"
                              repo: "https://concourse-charts.storage.googleapis.com"
                              version: "14.6.2"
                            output:
                              helmRelease:
                                useHelmReleaseStorage: true
                              additional:
                                useHelmTemplateStorage: true
                                goTemplate: |
                                  version: "{{ .Values.imageTag }}"
                                  host: "{{ (index .Values.web.ingress.hosts 0) }}"
                                  userAndPassword: "{{ .Values.secrets.localUsers }}"
                            values:
                              postgresql:
                                enabled: false
                              worker:
                                replicas: 1
                              rbac:
                                create: false
                              secrets:
                                postgresUser: <@ user.name @>
                                postgresPassword: <@ user.password @>
                              concourse:
                                web:
                                  externalUrl: https://<@ input.host @>
                                  kubernetes:
                                    createTeamNamespaces: false
                                  postgres:
                                    host: <@ db.host @>
                                    database: <@ database.name @>
                              web:
                                ingress:
                                  enabled: true
                                  annotations:
                                    acmechallengetype: http01
                                    cert-manager.io/cluster-issuer: letsencrypt
                                    kubernetes.io/ingress.class: nginx
                                    kubernetes.io/tls-acme: "true"
                                    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
                                  tls:
                                    - secretName: concourse-server-tls-<@ random_word(length=5) @>
                                      hosts:
                                        - <@ input.host @>
                                  hosts:
                                  - <@ input.host @>
                      - name: input-parameters
                        from: "{{steps.prepare-parameters.outputs.artifacts.merged}}"
                      - name: configuration
                        raw:
                          data: |

              - - name: helm-install
                  capact-action: helm.install
                  capact-outputTypeInstances:
                    - name: concourse-helm-release
                      from: helm-release
                  arguments:
                    artifacts:
                      - name: input-parameters
                        from: "{{steps.render-helm-args.outputs.artifacts.render}}"
                      - name: runner-context
                        from: "{{workflow.outputs.artifacts.runner-context}}"

              # allows reusing this workflow as a part of other umbrella workflows and read the artifact value
              - - name: resolve-value
                  template: resolve-ti-art-value
                  capact-outputTypeInstances:
                    - name: concourse-config
                      from: ti-artifact
                      backend: helm-template-storage
                  arguments:
                    artifacts:
                      - name: ti-artifact
                        from: "{{steps.helm-install.outputs.artifacts.additional}}"
                      - name: backend
                        from: "{{workflow.outputs.artifacts.helm-template-storage}}"

          - name: prepare-parameters
            inputs:
              artifacts:
                - name: input-parameters
                  path: /yamls/input.yaml
                - name: db
                  path: /yamls/db.yaml
                - name: database
                  path: /yamls/database.yaml
                - name: user
                  path: /yamls/user.yaml
            container:
              image: ghcr.io/capactio/infra/merger:2ada6f8
            outputs:
              artifacts:
              - name: merged
                path: /merged.yaml

          - name: resolve-ti-art-value
            inputs:
              artifacts:
                - name: ti-artifact
                  path: /tmp/input-ti.yaml
                - name: backend
                  path: /tmp/storage-backend.yaml
            outputs:
              artifacts:
                - name: ti-artifact
                  path: /tmp/output.yaml
            container:
              image: ghcr.io/capactio/pr/ti-value-fetcher:PR-707
              env:
                - name: APP_LOGGER_DEV_MODE
                  value: "true"
                - name: APP_INPUT_TI_FILE_PATH
                  value: "{{inputs.artifacts.ti-artifact.path}}"
                - name: APP_INPUT_BACKEND_TI_FILE_PATH
                  value: "{{inputs.artifacts.backend.path}}"
                - name: APP_OUTPUT_FILE_PATH
                  value: "{{outputs.artifacts.ti-artifact.path}}"
