ocfVersion: 0.0.1
revision: 0.1.0
kind: Type
metadata:
  name: storage
  prefix: cap.type.helm
  displayName: Helm chart storage
  description: Describes Helm storage
  documentationURL: https://helm.sh/docs
  supportURL: https://helm.sh
  maintainers:
    - email: team-dev@capact.io
      name: Capact Dev Team
      url: https://capact.io

spec:
  additionalRefs:
    - cap.core.type.hub.storage
  jsonSchema:
    value: |-
      {
          "$schema": "http://json-schema.org/draft-07/schema",
          "type": "object",
          "title": "The root schema",
          "required": [
              "url",
              "contextSchema",
              "acceptValue"
          ],
          "properties": {
              "url": {
                  "$id": "#/properties/url",
                  "type": "string",
                  "format": "uri"
              },
              "contextSchema": {
                  "const": {
                      "$schema": "http://json-schema.org/draft-07/schema",
                      "type": "object",
                      "required": [
                          "name",
                          "namespace"
                      ],
                      "properties": {
                          "name": {
                              "$id": "#/properties/context/properties/name",
                              "type": "string"
                          },
                          "namespace": {
                              "$id": "#/properties/context/properties/namespace",
                              "type": "string"
                          }
                      },
                      "additionalProperties": false
                  }
              },
              "acceptValue": {
                  "$id": "#/properties/acceptValue",
                  "type": "boolean",
                  "const": true
              }
          },
          "additionalProperties": false
      }
