ocfVersion: 0.0.1
revision: 0.1.0
kind: InterfaceGroup
metadata:
  prefix: cap.interface.database
  name: mongodb
  displayName: "MongoDB"
  description: "The database for modern applications"
  documentationURL: https://docs.mongodb.com/manual/
  supportURL: https://www.mongodb.com/
  iconURL: https://storage.googleapis.com/dashboard-icons/mongodb.svg
  maintainers:
    - email: team-dev@capact.io
      name: Capact Dev Team
      url: https://capact.io
