ocfVersion: 0.0.1
revision: 0.1.0
kind: InterfaceGroup
metadata:
  prefix: cap.interface.runner
  name: helm
  displayName: "Helm Runner"
  description: "Interfaces for Helm Runner actions"
  documentationURL: https://capact.io
  supportURL: https://capact.io
  iconURL: https://storage.googleapis.com/dashboard-icons/helm-icon.svg
  maintainers:
    - email: team-dev@capact.io
      name: Capact Dev Team
      url: https://capact.io
