ocfVersion: 0.0.1
revision: 0.1.0
kind: Interface
metadata:
  prefix: cap.interface.capactio.capact
  name: upgrade
  displayName: "Upgrade"
  description: "Upgrade action for Capact"
  documentationURL: https://capact.dev
  supportURL: https://capact.dev
  maintainers:
    - email: team-dev@capact.dev
      name: Capact Dev Team
      url: https://capact.dev

spec:
  input:
    parameters:
      input-parameters:
        typeRef:
          path: cap.type.capactio.capact.upgrade-input
          revision: 0.1.0

    typeInstances:
      capact-config:
        typeRef:
          path: cap.type.capactio.capact.config
          revision: 0.1.0
        verbs: [ "get", "update" ]
      capact-helm-release:
        typeRef:
          path: cap.type.helm.chart.release
          revision: 0.1.0
        verbs: [ "get", "update" ]
      argo-helm-release:
        typeRef:
          path: cap.type.helm.chart.release
          revision: 0.1.0
        verbs: [ "get", "update" ]
      ingress-nginx-helm-release:
        typeRef:
          path: cap.type.helm.chart.release
          revision: 0.1.0
        verbs: [ "get", "update" ]
      kubed-helm-release:
        typeRef:
          path: cap.type.helm.chart.release
          revision: 0.1.0
        verbs: [ "get", "update" ]
      monitoring-helm-release:
        typeRef:
          path: cap.type.helm.chart.release
          revision: 0.1.0
        verbs: [ "get", "update" ]
      neo4j-helm-release:
        typeRef:
          path: cap.type.helm.chart.release
          revision: 0.1.0
        verbs: [ "get", "update" ]
      cert-manager-helm-release:
        typeRef:
          path: cap.type.helm.chart.release
          revision: 0.1.0
        verbs: [ "get", "update" ]

  output:
    typeInstances:
      capact-config:
        typeRef:
          path: cap.type.capactio.capact.config
          revision: 0.1.0
