ocfVersion: 0.0.1
revision: 0.1.0
kind: Type
metadata:
  prefix: "cap.type.aws.redis"
  name: install-input
  displayName: "Input for AWS ElastiCache for Redis install"
  description: Input for the AWS ElastiCache Redis install Action
  documentationURL: https://redis.io/documentation
  supportURL: https://redis.io/support
  maintainers:
    - email: team-dev@capact.io
      name: Capact Dev Team
      url: https://capact.io
spec:
  jsonSchema:
    value: |-
      {
        "properties": {
          "region": {
            "type": "string",
            "title": "AWS region"
          },
          "apply_immediately": {
            "type": "boolean",
            "title": "apply_immediately",
            "description": "Specifies whether any modifications are applied immediately, or during the next maintenance window."
          },
          "at_rest_encryption_enabled": {
            "type": "boolean",
            "title": "at_rest_encryption_enabled",
            "description": "Whether to enable encryption at rest."
          },
          "auto_minor_version_upgrade": {
            "type": "string",
            "title": "auto_minor_version_upgrade"
          },
          "automatic_failover_enabled": {
            "type": "boolean",
            "title": "automatic_failover_enabled",
            "description": "Specifies whether a read-only replica will be automatically promoted to read/write primary if the existing primary fails."
          },
          "availability_zones": {
            "type": "array",
            "title": "availability_zones",
            "description": "A list of EC2 availability zones in which the replication group's cache clusters will be created. The order of the availability zones in the list is not important."
          },
          "cluster_mode_enabled": {
            "type": "boolean",
            "title": "cluster_mode_enabled",
            "description": "Enable creation of a native redis cluster."
          },
          "description": {
            "type": "string",
            "title": "description",
            "description": "The description of the all resources."
          },
          "engine_version": {
            "type": "string",
            "title": "engine_version",
            "description": "The version number of the cache engine to be used for the cache clusters in this replication group."
          },
          "family": {
            "type": "string",
            "title": "family",
            "description": "The family of the ElastiCache parameter group."
          },
          "final_snapshot_identifier": {
            "type": "string",
            "title": "final_snapshot_identifier",
            "description": "The name of your final node group (shard) snapshot. ElastiCache creates the snapshot from the primary node in the cluster. If omitted, no final snapshot will be made."
          },
          "global_replication_group_id": {
            "type": "string",
            "title": "global_replication_group_id",
            "description": "The ID of the global replication group to which this replication group should belong."
          },
          "ingress_cidr_blocks": {
            "type": "array",
            "title": "ingress_cidr_blocks",
            "description": "List of Ingress CIDR blocks."
          },
          "ingress_self": {
            "type": "boolean",
            "title": "ingress_self",
            "description": "Specify whether the security group itself will be added as a source to the ingress rule."
          },
          "kms_key_id": {
            "type": "string",
            "title": "kms_key_id",
            "description": "The ARN of the key that you wish to use if encrypting at rest. If not supplied, uses service managed encryption. Can be specified only if `at_rest_encryption_enabled = true`"
          },
          "maintenance_window": {
            "type": "string",
            "title": "maintenance_window",
            "description": "Specifies the weekly time range for when maintenance on the cache cluster is performed."
          },
          "multi_az_enabled": {
            "type": "string",
            "title": "multi_az_enabled",
            "description": "Specifies whether to enable Multi-AZ Support for the replication group. If true, `automatic_failover_enabled` must also be enabled. Defaults to false."
          },
          "node_type": {
            "type": "string",
            "title": "node_type",
            "description": "The compute and memory capacity of the nodes in the node group."
          },
          "notification_topic_arn": {
            "type": "string",
            "title": "notification_topic_arn",
            "description": "An Amazon Resource Name (ARN) of an SNS topic to send ElastiCache notifications to. Example: `arn:aws:sns:us-east-1:012345678999:my_sns_topic`"
          },
          "num_node_groups": {
            "type": "number",
            "title": "num_node_groups",
            "description": "Required when `cluster_mode_enabled` is set to true. Specify the number of node groups (shards) for this Redis replication group. Changing this number will trigger an online resizing operation before other settings modifications."
          },
          "number_cache_clusters": {
            "type": "number",
            "title": "number_cache_clusters",
            "description": "The number of cache clusters (primary and replicas) this replication group will have."
          },
          "parameter": {
            "type": "array",
            "title": "parameter",
            "description": "A list of Redis parameters to apply. Note that parameters may differ from one Redis family to another"
          },
          "port": {
            "type": "number",
            "title": "port",
            "description": "The port number on which each of the cache nodes will accept connections."
          },
          "replicas_per_node_group": {
            "type": "number",
            "title": "replicas_per_node_group",
            "description": "Required when `cluster_mode_enabled` is set to true. Specify the number of replica nodes in each node group. Valid values are 0 to 5. Changing this number will force a new resource."
          },
          "security_group_ids": {
            "type": "array",
            "title": "security_group_ids",
            "description": "List of Security Groups."
          },
          "snapshot_retention_limit": {
            "type": "number",
            "title": "snapshot_retention_limit",
            "description": "The number of days for which ElastiCache will retain automatic cache cluster snapshots before deleting them."
          },
          "snapshot_window": {
            "type": "string",
            "title": "snapshot_window",
            "description": "The daily time range (in UTC) during which ElastiCache will begin taking a daily snapshot of your cache cluster."
          },
          "subnet_ids": {
            "type": "array",
            "title": "subnet_ids",
            "description": "List of VPC Subnet IDs for the cache subnet group."
          },
          "tags": {
            "type": "object",
            "title": "tags",
            "description": "A mapping of tags to assign to all resources."
          },
          "transit_encryption_enabled": {
            "type": "boolean",
            "title": "transit_encryption_enabled",
            "description": "Whether to enable encryption in transit."
          },
          "vpc_id": {
            "type": "string",
            "title": "vpc_id",
            "description": "VPC Id to associate with Redis ElastiCache."
          }
        }
      }
