ocfVersion: 0.0.1
revision: 0.1.0
kind: Implementation
metadata:
  prefix: "cap.implementation.aws.secrets-manager"
  name: storage
  displayName: "storage Action"
  description: "storage Action"
  documentationURL: https://aws.amazon.com/secrets-manager/
  supportURL: https://aws.amazon.com/secrets-manager/
  iconURL: https://storage.googleapis.com/dashboard-icons/aws.svg
  maintainers:
    - email: team-dev@capact.io
      name: Capact Dev Team
      url: https://capact.io
  license:
    name: "Apache 2.0"

spec:
  appVersion: "1.0.x" # TODO(ContentDeveloper): Set the supported application version here
  additionalInput:
    parameters:
      additional-parameters:
        typeRef:
          path: "cap.type.aws.secrets-manager.storage-input-parameters"
          revision: 0.1.0

  outputTypeInstanceRelations:
    config:
      uses:
        - helm-release

  implements:
    - path: cap.interface.aws.secrets-manager.storage
      revision: 0.1.0

  requires:
    cap.core.type.platform:
      oneOf:
        - name: kubernetes
          revision: 0.1.0

  imports:
    - interfaceGroupPath: cap.interface.runner.argo
      alias: argo
      methods:
        - name: run
          revision: 0.1.0
    - interfaceGroupPath: cap.interface.templating.jinja2
      alias: jinja2
      methods:
        - name: template
          revision: 0.1.0
    - interfaceGroupPath: cap.interface.runner.helm
      alias: helm
      methods:
        - name: install
          revision: 0.1.0

  action:
    runnerInterface: argo.run
    args:
      workflow:
        entrypoint: deploy
        templates:
          - name: deploy
            inputs:
              artifacts:
                - name: input-parameters
                - name: additional-parameters
                  optional: true
            outputs:
              artifacts: []
            steps:
              - - name: prepare-parameters
                  template: prepare-parameters
                  arguments:
                    artifacts:
                      - name: input-parameters
                        from: "{{inputs.artifacts.input-parameters}}"
                      - name: additional-parameters
                        from: "{{inputs.artifacts.additional-parameters}}"
                        optional: true

              - - name: create-helm-args
                  capact-action: jinja2.template
                  arguments:
                    artifacts:
                      - name: input-parameters
                        from: "{{steps.prepare-parameters.outputs.artifacts.merged}}"
                      - name: configuration
                        raw:
                          data:
                      - name: template
                        raw:
                          data: |
                            generateName: true
                            chart:
                              name: "secret-storage-backend"
                              repo: ""
                              version: "0.6.0"
                            values: # TODO(ContentDeveloper): Adjust the input values to use parameters from the Interface
                              additionalEnvs: {}
                              affinity: {}
                              autoscaling:
                                enabled: <@ additionalinput.autoscaling.enabled | default(false) | tojson @>
                                maxReplicas: <@ additionalinput.autoscaling.maxReplicas | default(100) @>
                                minReplicas: <@ additionalinput.autoscaling.minReplicas | default(1) @>
                                targetCPUUtilizationPercentage: <@ additionalinput.autoscaling.targetCPUUtilizationPercentage | default(80) @>
                              global:
                                containerRegistry:
                                  overrideTag: <@ additionalinput.global.containerRegistry.overrideTag | default("latest") @>
                                  path: <@ additionalinput.global.containerRegistry.path | default("ghcr.io/capactio") @>
                              image:
                                name: <@ additionalinput.image.name | default("secret-storage-backend") @>
                                pullPolicy: <@ additionalinput.image.pullPolicy | default("IfNotPresent") @>
                              imagePullSecrets: <@ additionalinput.imagePullSecrets | default(None) | tojson @>
                              nodeSelector: {}
                              podAnnotations: {}
                              podSecurityContext: {}
                              replicaCount: <@ additionalinput.replicaCount | default(1) @>
                              resources:
                                limits:
                                  cpu: <@ additionalinput.resources.limits.cpu | default("100m") @>
                                  memory: <@ additionalinput.resources.limits.memory | default("32Mi") @>
                                requests:
                                  cpu: <@ additionalinput.resources.requests.cpu | default("30m") @>
                                  memory: <@ additionalinput.resources.requests.memory | default("16Mi") @>
                              securityContext: {}
                              service:
                                port: <@ additionalinput.service.port | default(50051) @>
                                type: <@ additionalinput.service.type | default("ClusterIP") @>
                              serviceAccount:
                                annotations: {}
                                create: <@ additionalinput.serviceAccount.create | default(true) | tojson @>
                                name: <@ additionalinput.serviceAccount.name | default("") | tojson @>
                              supportedProviders: <@ additionalinput.supportedProviders | default(["dotenv"]) @>
                              tolerations: <@ additionalinput.tolerations | default(None) | tojson @>
                              
                            output:
                              goTemplate: |
                                # TODO(ContentDeveloper): Add output template in YAML

              - - name: helm-install
                  capact-action: helm.install
                  capact-outputTypeInstances:
                    - name: helm-release
                      from: helm-release
                    - name: config
                      from: additional
                  arguments:
                    artifacts:
                      - name: input-parameters
                        from: "{{steps.create-helm-args.outputs.artifacts.render}}"
                      - name: runner-context
                        from: "{{workflow.outputs.artifacts.runner-context}}"

          - name: prepare-parameters
            inputs:
              artifacts:
                - name: input-parameters
                  path: /yamls/input.yaml
                - name: additional-parameters
                  path: /yamls/additionalinput.yaml
                  optional: true
            container:
              image: ghcr.io/capactio/pr/infra/merger:PR-428
            outputs:
              artifacts:
              - name: merged
                path: /merged.yaml
