ocfVersion: 0.0.1
revision: 0.1.0
kind: Interface
metadata:
  prefix: "cap.interface.database.redis"
  name: "install"
  displayName: "Install"
  description: "Install action for database Redis"
  documentationURL: https://redis.io/documentation
  supportURL: https://redis.io/support
  iconURL: https://redis.io/images/redis-white.png
  maintainers:
    - email: team-dev@capact.io
      name: Capact Dev Team
      url: https://capact.io

spec:
  input:
    parameters:
      input-parameters:
        typeRef:
          path: cap.type.database.redis.install-input
          revision: 0.1.0
    typeInstances: {}

  output:
    typeInstances:
      config:
        typeRef:
          path: cap.type.database.redis.config
          revision: 0.1.0
