ocfVersion: 0.0.1
revision: 0.1.0
kind: Implementation
metadata:
  prefix: cap.implementation.capactio.capact.examples.hello
  name: greet
  displayName: "Greet Capact"
  description: "Capact Greet Action"
  documentationURL: https://capact.dev
  supportURL: https://capact.dev
  license:
    name: "Apache 2.0"
  maintainers:
    - email: team-dev@capact.dev
      name: Capact Dev Team
      url: https://capact.dev

spec:
  appVersion: "0.3.x"
  outputTypeInstanceRelations: {}

  implements:
    - path: cap.interface.capactio.capact.examples.hello.greet
      revision: 0.1.0

  requires:
    cap.core.type.platform:
      oneOf:
        - name: kubernetes
          revision: 0.1.0

  imports:
    - interfaceGroupPath: cap.interface.runner.argo
      alias: argo
      methods:
        - name: run
          revision: 0.1.0
    - interfaceGroupPath: cap.interface.capactio.capact.examples.hello
      alias: capact
      methods:
        - name: say
          revision: 0.1.0

  action:
    runnerInterface: argo.run
    args:
      workflow:
        entrypoint: hello
        templates:
        - name: hello
          steps:
            - - name: say
                capact-action: capact.say
