ocfVersion: 0.0.1
revision: 0.1.0
kind: Interface
metadata:
  prefix: cap.interface.templating.jinja2
  name: template
  displayName: Jinja2 Template
  description: Generate output using Jinja2 template engine
  documentationURL: https://jinja.palletsprojects.com/en/2.11.x/
  supportURL: https://jinja.palletsprojects.com/en/2.11.x/
  iconURL: https://raw.githubusercontent.com/pallets/jinja/5f79ba633db0e6f56fc2d13cfc78547495f3d395/artwork/jinjalogo.svg
  maintainers:
    - email: team-dev@capact.io
      name: Capact Dev Team
      url: https://capact.io

spec:
  input:
    parameters:
      configuration:
        typeRef:
          path: cap.core.type.generic.value
          revision: 0.1.0
      input-parameters:
        typeRef:
          path: cap.core.type.generic.value
          revision: 0.1.0
      template:
        typeRef:
          path: cap.core.type.generic.value
          revision: 0.1.0

  output:
    typeInstances:
      render:
        typeRef:
          path: cap.core.type.generic.value
          revision: 0.1.0
