ocfVersion: 0.0.1
revision: 0.1.0
kind: Interface
metadata:
  prefix: cap.core.interface.runner.generic
  name: run
  displayName: "Run"
  description: "Run operation for generic Runner"
  documentationURL: https://capact.io
  supportURL: https://capact.io
  maintainers:
    - email: team-dev@capact.io
      name: Capact Dev Team
      url: https://capact.io

spec:
  input:
    parameters:
      input-parameters:
        typeRef:
          path: cap.core.type.generic.value
          revision: 0.1.0
    typeInstances:
      runner-context:
        typeRef:
          path: cap.core.type.runner.generic.context
          revision: 0.1.0
        verbs: [ "get" ]
  output: {}
