ocfVersion: 0.0.1
revision: 0.1.0
kind: Type
metadata:
  prefix: cap.type.database.object.aws.s3
  name: bucket-config
  displayName: S3 bucket config
  description: AWS S3 bucket config
  documentationURL: https://aws.amazon.com/s3/
  supportURL: https://aws.amazon.com/s3/
  maintainers:
    - email: team-dev@capact.io
      name: Capact Dev Team
      url: https://capact.io

spec:
  jsonSchema:
    value: |-
      {
        "$schema": "http://json-schema.org/draft-07/schema",
        "type": "object",
        "title": "The schema for S3 bucket config",
        "examples": [
          {
            "name": "bucket"
          }
        ],
        "required": [
           "name"
        ],
        "properties": {
          "name": {
            "$id": "#/properties/name",
            "type": "string",
            "title": "Defines a bucket name"
          }
        },
        "additionalProperties": false
      }
