ocfVersion: 0.0.1
revision: 0.1.0
kind: Type
metadata:
  prefix: cap.type.database.object.aws.s3
  name: install-input
  displayName: Input for AWS S3
  description: Input for AWS S3 object store
  documentationURL: https://aws.amazon.com/s3/
  supportURL: https://aws.amazon.com/s3/
  maintainers:
    - email: team-dev@capact.io
      name: Capact Dev Team
      url: https://capact.io
spec:
  jsonSchema:
    value: |-
      {
        "$schema": "http://json-schema.org/draft-07/schema",
        "type": "object",
        "title": "The schema for S3 installation input",
        "examples": [
          {
            "name": "Cluster name",
            "accesskey": "foo",
            "secretkey": "bar"
          }
        ],
        "required": [
           "name"
        ],
        "properties": {
          "name": {
            "$id": "#/properties/name",
            "type": "string",
            "title": "S3 installation name"
          },
          "accesskey": {
            "$id": "#/properties/accesskey",
            "type": "string",
            "title": "Access Key"
          },
          "secretkey": {
            "$id": "#/properties/secretkey",
            "type": "string",
            "title": "Secret Key"
          }
        },
        "additionalProperties": false
      }
