ocfVersion: 0.0.1
revision: 0.1.0
kind: InterfaceGroup
metadata:
  prefix: cap.interface.capactio.capact.validation
  name: hub
  displayName: "Capact E2E Hub Public test manifests"
  description: "Manifests used for testing Hub Public GraphQL calls and filters"
  documentationURL: https://capact.io
  supportURL: https://capact.io
  maintainers:
    - email: team-dev@capact.io
      name: Capact Dev Team
      url: https://capact.io
