ocfVersion: 0.0.1
revision: 0.1.0
kind: Type
metadata:
  prefix: "cap.type.database.redis"
  name: config
  displayName: "Database Redis config"
  description: "Type representing a database Redis config"
  documentationURL: https://redis.io/documentation
  supportURL: https://redis.io/support
  iconURL: https://redis.io/images/redis-white.png
  maintainers:
    - email: team-dev@capact.io
      name: Capact Dev Team
      url: https://capact.io
spec:
  jsonSchema:
    value: |-
      {
        "$schema": "http://json-schema.org/draft-07/schema",
        "type": "object",
        "title": "The schema for Redis configuration",
        "examples": [
          {
            "password": "pass"
          }
        ],
        "required": [
          "host",
          "port",
          "password"
        ],
        "definitions": {
          "hostname": {
            "type": "string",
            "format": "hostname",
            "title": "Hostname"
          },
          "port": {
            "type": "integer",
            "title": "Port",
            "minimum": 0,
            "maximum": 65535
          }
        },
        "properties": {
          "password": {
            "$id": "#/properties/rootPassword",
            "type": "string",
            "title": "Defines a database password"
          },
          "host": {
            "$ref": "#/definitions/hostname"
          },
          "port": {
            "$ref": "#/definitions/port"
          }
        },
        "additionalProperties": false
      }
