ocfVersion: 0.0.1
revision: 0.1.0
kind: Type
metadata:
  name: generic
  prefix: cap.core.type.hub.storage
  displayName: Generic storage backend schema
  description: Defines schema which is used for validation of backend storages.
  documentationURL: https://capact.io/docs
  supportURL: https://capact.io
  maintainers:
    - email: team-dev@capact.io
      name: Capact Dev Team
      url: https://capact.io
spec:
  jsonSchema:
    value: |-
      {
        "$schema": "http://json-schema.org/draft-07/schema",
        "type": "object",
        "title": "The generic storage backend schema",
        "required": [
          "required"
        ],
        "properties": {
          "required": {
            "$id": "#/properties/required",
            "type": "array",
            "minItems": 3,
            "allOf": [
              {
                "contains": {
                  "const": "url"
                }
              },
              {
                "contains": {
                  "const": "acceptValue"
                }
              },
              {
                "contains": {
                  "const": "contextSchema"
                }
              }
            ]
          }
        }
      }
