name: Default branch build

on:
  push:
    paths-ignore:
      - "LICENSE"
      - "CODEOWNERS"
      - "README.md"
    branches:
      - main

jobs:
  validation:
    name: Validate Hub manifests
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download the latest Capact CLI for linux
        run: |
          curl -Lo ./capact https://storage.googleapis.com/capactio-binaries/latest/capact-linux-amd64
          chmod +x ./capact

      - name: Validate manifests
        run: |
          ./capact manifest validate $(find ./manifests -regex ".*\.yaml")
